### ISSUE TITLE
Set up proper Javascript / ES6 pipeline

### ISSUE THREAD

**Issue by lucky-bai** [y629wang/sleep-learner#1]
This will allow us to use require, and ES6 classes. Look into babel and browserify, maybe webpack.

**Comment by rainsoupah** [comment]
webpack incorporation with python is rather difficult :/ maybe react doesnt work well with python (sorry for suggesting it in the first place)

**Comment by lucky-bai** [comment]
Webpack is annoying, but I'm sort-of successful with setting up Bower + Babel CLI.

So right now, ES6 and JSX transpiling work, but imports don't work (so you have to put all JS dependencies in the html file). Also when you change JS, you have to restart `make dev`. Marking this as done.
